# Generated by Django 5.2.1 on 2025-05-29 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('clubhouse', models.IntegerField()),
                ('sqrt', models.IntegerField()),
                ('estate_size', models.FloatField(default=0.0)),
                ('is_published', models.DateTimeField(default=True)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo_1', models.ImageField(upload_to='photos/%Y/%m/%d/, blank=True')),
                ('photo_2', models.ImageField(upload_to='photos/%Y/%m/%d/, blank=True')),
                ('photo_3', models.ImageField(upload_to='photos/%Y/%m/%d/, blank=True')),
                ('photo_4', models.ImageField(upload_to='photos/%Y/%m/%d/, blank=True')),
                ('photo_5', models.ImageField(upload_to='photos/%Y/%m/%d/, blank=True')),
                ('photo_6', models.ImageField(upload_to='photos/%Y/%m/%d/, blank=True')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor')),
            ],
        ),
    ]
