# Generated by Django 5.2.1 on 2025-05-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listings_delete_listing'),
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listings',
            options={'ordering': ('-list_date',)},
        ),
        migrations.AddIndex(
            model_name='listings',
            index=models.Index(fields=['list_date'], name='listings_li_list_da_bc48b9_idx'),
        ),
    ]
