# Generated by Django 5.2.1 on 2025-06-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_alter_listings_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listings",
            name="district",
            field=models.CharField(
                choices=[
                    ("Islands", "Islands"),
                    ("Kwai Tsing", "Kwai Tsing"),
                    ("North", "North"),
                    ("Sai Kung", "Sai Kung"),
                    ("Sha Tin", "Sha Tin"),
                    ("Tai Po", "Tai Po"),
                    ("Tuen Mun", "Tuen Mun"),
                    ("Tsuen Wan", "Tsuen Wan"),
                    ("Yuen Long", "Yuen Long"),
                    ("Kowloon City", "Kowloon City"),
                    ("Kwun Tong", "Kwun Tong"),
                    ("Sham Shui Po", "Shum Shui Po"),
                    ("Wang Tai Sin", "Wong Tai Sin"),
                    ("Yau Tsim Mong", "Yau Tsim Mong"),
                    ("Central & Western", "Central & Western"),
                    ("Eastern", "Eastern"),
                    ("Southern", "Southern"),
                    ("Wan Chai", "Wan Chai"),
                ],
                max_length=50,
            ),
        ),
    ]
