# Generated by Django 5.2.1 on 2025-05-29 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='hire_rate',
            new_name='hire_date',
        ),
    ]
